spring:
#  application:
#    name: learn
  datasource:
    url: jdbc:postgresql://localhost:5432/learn
    username: postgres
    password: evblood123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    secret-key: ;gknfbngjbgoeibrgo[ibergotubgvn sb23j]34-9u]giq3 j
server:
  port: 80
